name: Android

# spell-checker:ignore TERMUX reactivecircus Swatinem  noaudio pkill swiftshader dtolnay juliangruber

on:
  pull_request:
  push:
    branches:
      - main


permissions:
  contents: read # to fetch code (actions/checkout)

# End the current execution if there is a new changeset in the PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  TERMUX: v0.118.0
  KEY_POSTFIX: nextest+rustc-hash+adb+sshd+upgrade+XGB+inc18
  COMMON_EMULATOR_OPTIONS: -no-window -noaudio -no-boot-anim -camera-back none -gpu swiftshader_indirect
  EMULATOR_DISK_SIZE: 12GB
  EMULATOR_HEAP_SIZE: 2048M
  EMULATOR_BOOT_TIMEOUT: 1200 # 20min

jobs:
  test_android:
    name: Test builds
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        include:
        - { api-level: 28, arch: x86, cores: 4, target: google_apis_playstore, os: ^ubuntu-latest }
        - { api-level: 28, arch: x86_64, cores: 4, target: google_apis_playstore, os: ubuntu-latest }
        - { api-level: 29, arch: x86, cores: 4, target: google_apis_playstore, os: ubuntu-latest }
        - { api-level: 29, arch: x86_64, cores: 4, target: default, os: ubuntu-latest }
        - { api-level: 30, arch: x86, cores: 4, target: google_apis, os: ubuntu-latest }
        - { api-level: 30, arch: x86_64, cores: 4, target: google_apis, os: ubuntu-latest }
        - { api-level: 31, arch: x86_64, cores: 4, target: default, os: ubuntu-latest }
        - { api-level: 32, arch: x86_64, cores: 4, target: default, os: ubuntu-latest }
        - { api-level: 33, arch: x86_64, cores: 4, target: default, os: ubuntu-latest }
        - { api-level: 34, arch: x86_64, cores: 4, target: default, os: ubuntu-latest }
    runs-on: ubuntu-latest
    env:
      EMULATOR_RAM_SIZE: ${{ matrix.ram }}
      EMULATOR_CORES: ${{ matrix.cores }}
      RUNNER_OS: ${{ matrix.os }}
      AVD_CACHE_KEY: "set later due to limitations of github actions not able to concatenate env variables"
    steps:
    - name: Concatenate values to environment file
      run: |
        echo "os: ${{ matrix.os }}, cores: ${{ matrix.cores }}, ram: ${{ matrix.ram }},
        echo "api-level: ${{ matrix.api-level }}, target: ${{ matrix.target }}, arch: ${{ matrix.arch }}
        echo "matrix: ${{ matrix }}"
